### ISSUE TITLE
Models - WizardLM-7b

### ISSUE THREAD

**Issue by gururise** [idosal/AgentLLM#6]
In my testing, [WizardLM-7b](https://github.com/nlpxucan/WizardLM) model is superior to vicuna-7b in terms of following complex instructions, especially langchain style prompting.  Would it be possible to add a feature where one could select the model to be loaded?

**Comment by idosal** [comment]
I'm happy to say I've generated the WizardLM-7b model locally. I'm still ironing out some kinks but it should be available in upcoming versions. Stay tuned!

**Comment by idosal** [comment]
WizardLM-7b is live!
