### ISSUE TITLE
Offline use not possible - request to huggingface...ndarray-cache.json

### ISSUE THREAD

**Issue by MaunoKoponen** [idosal/AgentLLM#9]
I installed fork to Win environment, and there were no erors, and the Process starts ok  - althoug having also error [(https://github.com/idosal/AgentLLM/issues/7)]
When I try to use the agent offline, there is error, since program tries to connect to hugginface: 
Entering new llm_chain chain...
console.js:13 Starting (...) with name webLlm with prompts: You have the following objective: `plan a trip to Havaji`. Create a list of zero to three tasks to be completed by you such that your goal is more closely reached or completely reached. The response list MUST be a SINGLE ARRAY OF STRINGS where each string is a TASK NAME wrapped in quotes (EXAMPLE OF RESPONSE FORMAT: "["task name", "task name"]"). You MUST be able to parse the list with Javascript’s JSON.parse() function. You must respond with the array WITHOUT ANY OTHER TEXT.

tvmjs_runtime.wasi.js:2660     GET https://huggingface.co/mlc-ai/web-lm/resolve/main/vicuna-7b-v1/ndarray-cache.json net::ERR_INTERNET_DISCONNECTED

The json can be fetced easily if the connection is open.  Does the  json need to be fetced, could it be local? Or is my setup just broken?

**Comment by idosal** [comment]
You're right, downloading the cache file the first time the tab is loaded is a limitation in the current version. The good news is that it'll be fixed in the next versions!

**Comment by idosal** [comment]
It's now cached and fetched locally!
